-- MariaDB Schema for WhatsApp Song Scanner
-- This schema is auto-generated by SQLAlchemy models
-- Use this file for reference or manual database setup

-- Character set and collation
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET COLLATION_CONNECTION = 'utf8mb4_unicode_ci';

-- Create database
CREATE DATABASE IF NOT EXISTS song_scanner
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE song_scanner;

-- WhatsApp Chats Table
CREATE TABLE IF NOT EXISTS whatsapp_chats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chat_id VARCHAR(255) NOT NULL UNIQUE,
    chat_name VARCHAR(255),
    last_message_id VARCHAR(255),
    last_scan_time DATETIME,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_chat_id (chat_id),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(255) NOT NULL UNIQUE,
    chat_id VARCHAR(255) NOT NULL,
    sender_number VARCHAR(50),
    sender_name VARCHAR(255),
    raw_text TEXT NOT NULL,
    cleaned_text TEXT,
    timestamp DATETIME NOT NULL,
    is_processed BOOLEAN DEFAULT FALSE,
    processing_attempts INT DEFAULT 0,
    processing_error TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES whatsapp_chats(chat_id) ON DELETE CASCADE,
    INDEX idx_message_id (message_id),
    INDEX idx_chat_id (chat_id),
    INDEX idx_timestamp (timestamp),
    INDEX idx_is_processed (is_processed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Extracted Songs Table
CREATE TABLE IF NOT EXISTS extracted_songs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message_id INT NOT NULL,
    original_phrase VARCHAR(500) NOT NULL,
    confidence_score FLOAT,
    extraction_method VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    INDEX idx_message_id (message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Matched Songs Table
CREATE TABLE IF NOT EXISTS matched_songs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    extraction_id INT NOT NULL,
    song_title VARCHAR(500) NOT NULL,
    artist_name VARCHAR(500),
    album_name VARCHAR(500),
    musicbrainz_id VARCHAR(255),
    spotify_id VARCHAR(255),
    deezer_id VARCHAR(255),
    match_confidence FLOAT,
    match_source VARCHAR(50),
    match_metadata JSON,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_method VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (extraction_id) REFERENCES extracted_songs(id) ON DELETE CASCADE,
    INDEX idx_song_title (song_title(255)),
    INDEX idx_artist_name (artist_name(255)),
    INDEX idx_musicbrainz_id (musicbrainz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Song Requests Table
CREATE TABLE IF NOT EXISTS song_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chat_id VARCHAR(255) NOT NULL,
    matched_song_id INT NOT NULL,
    requested_by VARCHAR(255),
    request_priority INT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'pending',
    radiodj_playlist_id INT,
    radiodj_track_id INT,
    scheduled_play_time DATETIME,
    actual_play_time DATETIME,
    play_count INT DEFAULT 0,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES whatsapp_chats(chat_id) ON DELETE CASCADE,
    FOREIGN KEY (matched_song_id) REFERENCES matched_songs(id) ON DELETE CASCADE,
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
